### ISSUE TITLE
Docs include description of CONJUR_FOLLOWER_URL environment variable

### ISSUE THREAD

**Issue by jtuttle** [cyberark/docs-cyberark-conjur-service-broker#3]
The Conjur service broker can now be configured with the `CONJUR_FOLLOWER_URL` environment variable, which should be set to the URL of a load balancer managing Conjur followers when using a high availability cluster. During the bind request, it will be returned to the application as the URL with which to communicate with Conjur.

**Comment by izgeri** [comment]
I've merged this update into #5 - closing this issue as a duplicate now
