### ISSUE TITLE
Docs include description of Service Broker Auto-creating org and space layers on Provision for PCF 2.0+

### ISSUE THREAD

**Issue by micahlee** [cyberark/docs-cyberark-conjur-service-broker#4]
There are two service broker behaviors that need to be updated in the docs:

- The policy structure documented in #2 will be created automatically if it doesn't exist when the service broker is provisioned in a CF space.

- By default, the service broker will also clean up these policy branches and layers when the service broker is de-provisioned from a space. This clean-up can be skipped to keep the policy structure intact by configuring the service broker with `CONJUR_PRESERVE_POLICY=true`.
    > Per https://github.com/cyberark/conjur-service-broker/pull/76#discussion_r256986175:
    > The value of this variable should be either `true` or `false`

**Comment by izgeri** [comment]
I've added notes about making these changes in #5; closing this issue as a duplicate now.
