### ISSUE TITLE
Update doc for new tile release

### ISSUE THREAD

**Issue by izgeri** [cyberark/docs-cyberark-conjur-service-broker#41]
Review the CHANGELOGs for the service-broker and buildpack to determine if any additional features need to be documented. Also review https://github.com/cyberark/conjur-service-broker/pull/248 to see if this needs to be documented.

**Comment by jtuttle** [comment]
Tile v1.3.0 docs released (https://docs.pivotal.io/partners/cyberark-conjur-service-broker/index.html).
